# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for boilerplate

  target 'boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'boilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'boilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for boilerplate-tvOS

  target 'boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
